from invenio.sqlalchemyutils import db


domain = "drihm"
display_name = "DRIHM"
table_name = 'drihm'
image = 'drihm_icon.jpg'
kind = 'project'

# note that fields will need more stuff like validators later
fields = [{'name':'hydrology',
           'display_text':'Hydrology',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'hydraulic',
           'display_text':'Hydraulic',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'meteorology',
           'display_text':'Meteorology',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'flooding',
           'display_text':'Flooding',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'storm',
           'display_text':'Storm',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'citizenscientist',
           'display_text':'Citizen Scientist',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'observation',
           'display_text':'Observation',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'research',
           'display_text':'Research',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'data',
           'display_text':'Data',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'model',
           'display_text':'Model',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'rainfall',
           'display_text':'Rainfall',
           'col_type':db.Double(),
           'mandatory':False,
           'extra':False},
          {'name':'discharge',
           'display_text':'Discharge',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'hydrograph',
           'display_text':'Hydrograph',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'rainguage',
           'display_text':'Rain Guage',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'weather',
           'display_text':'Weather',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False},
          {'name':'experiment',
           'display_text':'Experiment',
           'col_type':db.String(256),
           'mandatory':False,
           'extra':False}]
