# -*- coding: utf-8 -*-
#
# This file is part of EUDAT B2Share.
# Copyright (C) 2016 University of Tuebingen, CERN.
# Copyright (C) 2015 University of Tuebingen.
#
# B2Share is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# B2Share is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with B2Share; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""B2SHARE Community module.

B2SHARE datasets belong to different communities. A community is characterized
by:

    * A name.
    * The datasets it owns. See later the **records** section.
    * **Member** and **Admin** roles which can be assigned to specific users in
      order to limit access to records.
    * A versioned JSON schema validating its datasets' metadata.

There is no clear definition of a community. Some communities are
just publishing the datasets of an organization. Others, like the "EUDAT"
community on ``b2share.eudat.eu`` enable any authenticated user to publish
datasets. Thus a community could be a whole organization, an experiment, a
team or just a place to publish datasets.

The **Community Administrators** are in charge of:

* accepting the new **Community Members**.
* reviewing datasets before they are published (see *deposits* and publication
  workflow). This feature is at this time in progress.

Community Administrators are currently assigned by a B2SHARE service
**superuser**.

The **Community Members** are chosen by the Community Administrators. They
can submit datasets when a community has restricted submissions access.

The JSON schema provided by communities are generated by the
``b2share.modules.schemas`` module.

An OAI set is also created for each community. This enables to harvest
all the datasets (aka records) via the OAI-PMH endpoint. This is for example
used by the B2Find service. see ``invenio-oaiserver``.

**Future Work:**

REST API: This module is for now pretty simple in that the communities are
created via CLI. However Some work has been started to enable Community
creation via REST API.
"""

from __future__ import absolute_import, print_function

from .ext import B2ShareCommunities
from .api import Community

__all__ = ('B2ShareCommunities', 'Community')
