Vagrant.configure("2") do |config|
  config.vm.define "default" do |c|
    c.vm.box = "chef/centos-7.0"
    c.vm.box_url = "https://vagrantcloud.com/chef/boxes/centos-7.0"
    c.vm.provision :shell, path: "./provision_system.sh"
    c.vm.network :forwarded_port, guest:4000, host: 4000
    c.vm.network :forwarded_port, guest:4443, host: 4443
    c.vm.network :forwarded_port, guest:3306, host: 9306

    c.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end

    puts " *** Please run ./install.sh to install B2SHARE in your new VM ***"
    puts "     If B2SHARE is already installed, go into the VM and you can start it with:"
    puts "     # /vagrant/start_b2share.sh"
  end
end
