Vagrant.configure("2") do |config|
  config.vm.box = "centos65x64"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"

  config.vm.network :forwarded_port, guest:4000, host: 4000
  config.vm.network :forwarded_port, guest:4443, host: 4443
  config.vm.provision :shell, path: ".vagrant/bootstrap/provision.sh"
#  config.vm.synced_folder "../invenio/", "/home/vagrant/.virtualenvs/b2share/src/b2share/invenio"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

end
