
INVENIO_SCRIPTS_REPO = File.absolute_path(File.dirname(__FILE__) + "/../../")
B2SHARE_DEV_REPO = File.absolute_path(File.dirname(__FILE__) + "/../../b2share/")

Vagrant.configure("2") do |config|
  config.vm.define "default" do |c|
    c.vm.box = "centos65x64"
    c.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"

    c.vm.network :forwarded_port, guest:4000, host: 4000
    c.vm.network :forwarded_port, guest:4443, host: 4443
    c.vm.provision :shell, path: ".vagrant/bootstrap/provision.sh"
    c.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  config.vm.define "dev" do |c|
    c.vm.box = "centos65x64"
    c.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"
    c.vm.provision :shell, path: ".vagrant/bootstrap/provision-dev.sh"
    c.vm.network :forwarded_port, guest:4000, host: 4000
    c.vm.network :forwarded_port, guest:4443, host: 4443
    c.vm.network :forwarded_port, guest:3306, host: 9306
    if File.exists? B2SHARE_DEV_REPO
      c.vm.synced_folder B2SHARE_DEV_REPO, "/home/vagrant/.virtualenvs/b2share/src/b2share"
    else
      q = []
      q << "  B2SHARE repository not found in: `#{B2SHARE_DEV_REPO}`"
      q << "  - Consider cloning a version of B2SHARE:"
      q << "    $ cd #{INVENIO_SCRIPTS_REPO}"
      q << "    $ git clone -b master https://github.com/EUDAT-B2SHARE/b2share.git"
      puts q.join("\n")
      exit 1
    end
    c.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end
end
